name: /home/egozo/Research/workdir/scripts/python/bias_adjustment/.venv
channels:
  - conda-forge
  - defaults
dependencies:
  - mamba
  - python>=3.8.1,<3.9
  - poetry=1
  - conda-lock
platforms:
  - linux-64