[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bias_adjustment"
version = "0.1.0"
description = "Bias Adjustment by Quantile Mapping"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Emilio Gozo", email = "emiliogozo@proton.me" }
]
keywords = ["climatology", "data analysis", "quantile mapping", "bias correction"]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "numpy",
    "scipy",
]

[project.optional-dependencies]
tests = [
  "pytest",
]

[tool.pytest.ini_options]
pythonpath = "src/"
