name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: toolbox
        environment-file: environment.yml
    - name: Install dependencies
      run: poetry install
    - name: Test
      run: poetry run pytest
