name: Python Package using Conda

on: [push]

jobs:
  miniforge:
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: devbox
          environment-file: etc/dev.yml
          miniforge-version: latest
      - name: Test
        run: tox -e py310,py311,py312
